### ISSUE TITLE
Section tag-indən istifadə

### ISSUE THREAD

**Issue by EldanizAkbar** [isgandarhasilov/PragmatechFoundationProject#1]
https://github.com/isgandarhasilov/PragmatechFoundationProject/blob/23c75ae5421cac639debc2684126b590fc560d6c/Project/index.html#L28

Zəhmət olmasa website-ı hissələrə ayır. Hər bir hissəni də bir `section ` tag-ındə yaz. Hamısını ümumi bir section tag-ində yazmağa ehtiyac yoxdu.

**Comment by isgandarhasilov** [comment]
Salam @EldanizAkbar @isgandarhasilov  düzəlişlər edildi.
