### ISSUE TITLE
Bəzi tapşırıqlar

### ISSUE THREAD

**Issue by EldanizAkbar** [isgandarhasilov/PragmatechFoundationProject#2]
Zəhmət olmasa aşağıdakı problemləri tez bir zamanda həll et.

- [x] Layihəndə **html** fayllarını bir qovluğa yığ.
- [x] Yazdığın **html** faylları arasında əlaqə yoxdu. Zəhmət olmasa onları əlaqələndir.

**Comment by isgandarhasilov** [comment]
Salam  @EldanizAkbar göstərilən problemlər həll edildi.
