### ISSUE TITLE
Scrolun aradan qaldırılması

### ISSUE THREAD

**Issue by EldanizAkbar** [isgandarhasilov/PragmatechFoundationProject#3]
Layihəndə Haqqımda səhifəsində **scrol** yaranıb. Zəhmət olmasa onu aradan qaldır.

**Comment by isgandarhasilov** [comment]
Salam @EldanizAkbar layihədə baxdım scroll yaranıb orda, ona görə götürmədim. Layihəmin linki budu - https://lmpixels.com/demo/sunshine-demo/sunshine-version-1/sunshine-v1-html-template-green-cyan/index.html#about_me

**Comment by EldanizAkbar** [comment]
> Salam @EldanizAkbar layihədə baxdım scroll yaranıb orda, ona görə götürmədim. Layihəmin linki budu - https://lmpixels.com/demo/sunshine-demo/sunshine-version-1/sunshine-v1-html-template-green-cyan/index.html#about_me

Bu linkdə axı üfüqi şəkildə scroll yoxdu. Sadəcə şaquli şəkildə var. Səndə isə scroll həm şaquli yaranıb həm də üfüqi. Üfüqi scroll olmamalıdı

**Comment by isgandarhasilov** [comment]
Hə indi fikir verdim məndə, diqqətimdən qaçıb o hissə çox sağ ol @EldanizAkbar 
Göstərilən scroll aradan qaldırıldı, problem fix edilid və repo update olundu.
